services:
  # ===== 開発環境（デフォルト） =====
  aivis:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./AivisSpeech-Engine-Dev:/home/user/.local/share/AivisSpeech-Engine-Dev
    environment:
      # - VV_WORKERS=1
      - VV_WORKERS=4
    #   - VV_MAX_REQUESTS=1000
    #   - VV_ENABLE_TRACING=0
    # command: ["gunicorn", "-c", "gunicorn_conf.py", "app_factory:app"]
    # profiles:
      # - dev

  # # ===== 本番環境（Gunicorn + 複数ワーカー） =====
  # aivis-prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./AivisSpeech-Engine-Dev:/home/user/.local/share/AivisSpeech-Engine-Dev
  #   ports:
  #     - 10102:10101
  #   environment:
  #     - VV_WORKERS=4
  #     - VV_TIMEOUT=120
  #     - VV_MAX_REQUESTS=1000
  #   command: ["gunicorn", "-c", "gunicorn_conf.py", "app_factory:app"]
  #   profiles:
  #     - prod
  #     - benchmark

  # ===== 負荷テストツール（Locust） =====
  locust:
    image: locustio/locust:2.20.0
    ports:
      - 8089:8089
    volumes:
      - ./test/benchmark:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://aivis:10101
    depends_on:
      - aivis
    # profiles:
    #   - benchmark

